### PR TITLE
Cln/better errors

### PR DESCRIPTION
**Pull request by carols10cents**
It's tough to really assess the causes of the bunchball errors we're seeing because they have generic runtime errors with generic messages. This gives more information in the exception itself, which should give us better error grouping.

To test:
- [ ] Use the branch of apangea that uses this branch, deploy to a farm, do some bunchball things and see what errors you get?

### CODE REVIEW

**Comment by carols10cents** [comment]
Running tests on apangea https://github.com/thinkthroughmath/apangea/pull/1940

**Comment by laboon** [comment]
@carols10cents Just a couple of questions to ensure I understand, but otherwise looks good to go.  Will flip to Passed CR.

**Comment by carols10cents** [comment]
@laboon your comment made me realize that the valid? and error methods on response didn't even make sense anymore, so I removed those. wdyt?

**Comment by srobbibaro** [comment]
@laboon  - I noticed that there hasn't been movement on this PR for a while. Is this something you're planning to look into? Is there anything blocking you or any way that I can help?

**Comment by laboon** [comment]
?? The last movement was yesterday afternoon, right before I had to leave to take care of Calvin.  I will look at the changes this morning.

**Comment by laboon** [comment]
I like the .valid? refactoring, and in light of the fact that BB hasn't updated this code since 2012, I say removing the tests is fine.

**Comment by srobbibaro** [comment]
Sorry, I was blanket sending those out to the all the PRs which were over a certain number of hours since they've been touched. Mostly I just wanted to make sure it was something that you still wanted to (and could given circumstances). There's absolutely no rush! I know you're not on the clock until 9:30. I made a resolution to be a little more proactive regarding ensuring that PRs aren't left to sit too long, but maybe I'll have to rethink my approach/messaging. Sorry. :(

**Comment by laboon** [comment]
LGTM!  Good work @carols10cents

**Comment by srobbibaro** [comment]
Thanks, @laboon !!

**Comment by carols10cents** [comment]
Ok since apangea has the version locked to the SHA, I'm going to merge this here and submit a PR that updates the bunchball SHA in apangea for QA. That is, the merge here will not affect production at all. We can't really QA this without apangea anyway.

**Comment by el-jefe-** [comment]
thanks Carol!

**Pull request merged**
